/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/complete`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/subject`; params?: Router.UnknownInputParams; } | { pathname: `/recording`; params?: Router.UnknownInputParams; } | { pathname: `/report/strategy`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/add`; params?: Router.UnknownInputParams; } | { pathname: `/students/add`; params?: Router.UnknownInputParams; } | { pathname: `/students`; params?: Router.UnknownInputParams; } | { pathname: `/test`; params?: Router.UnknownInputParams; } | { pathname: `/test/report`; params?: Router.UnknownInputParams; } | { pathname: `/exam/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/parent-report/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } } | { pathname: `/report/[token]`, params: Router.UnknownInputParams & { token: string | number; } } | { pathname: `/students/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/test/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/complete`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/subject`; params?: Router.UnknownOutputParams; } | { pathname: `/recording`; params?: Router.UnknownOutputParams; } | { pathname: `/report/strategy`; params?: Router.UnknownOutputParams; } | { pathname: `/sessions/add`; params?: Router.UnknownOutputParams; } | { pathname: `/students/add`; params?: Router.UnknownOutputParams; } | { pathname: `/students`; params?: Router.UnknownOutputParams; } | { pathname: `/test`; params?: Router.UnknownOutputParams; } | { pathname: `/test/report`; params?: Router.UnknownOutputParams; } | { pathname: `/exam/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/parent-report/[sessionId]`, params: Router.UnknownOutputParams & { sessionId: string; } } | { pathname: `/report/[token]`, params: Router.UnknownOutputParams & { token: string; } } | { pathname: `/students/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/test/[sessionId]`, params: Router.UnknownOutputParams & { sessionId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/onboarding/calendar${`?${string}` | `#${string}` | ''}` | `/onboarding/complete${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/subject${`?${string}` | `#${string}` | ''}` | `/recording${`?${string}` | `#${string}` | ''}` | `/report/strategy${`?${string}` | `#${string}` | ''}` | `/sessions/add${`?${string}` | `#${string}` | ''}` | `/students/add${`?${string}` | `#${string}` | ''}` | `/students${`?${string}` | `#${string}` | ''}` | `/test${`?${string}` | `#${string}` | ''}` | `/test/report${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/complete`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/subject`; params?: Router.UnknownInputParams; } | { pathname: `/recording`; params?: Router.UnknownInputParams; } | { pathname: `/report/strategy`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/add`; params?: Router.UnknownInputParams; } | { pathname: `/students/add`; params?: Router.UnknownInputParams; } | { pathname: `/students`; params?: Router.UnknownInputParams; } | { pathname: `/test`; params?: Router.UnknownInputParams; } | { pathname: `/test/report`; params?: Router.UnknownInputParams; } | `/exam/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/parent-report/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/report/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/students/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/test/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/exam/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/parent-report/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } } | { pathname: `/report/[token]`, params: Router.UnknownInputParams & { token: string | number; } } | { pathname: `/students/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/test/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } };
    }
  }
}
