import React, { useState, useEffect } from 'react';
import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    ScrollView,
    ActivityIndicator,
    Dimensions,
    Share,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, radius } from '../../constants/theme';
import { analyzeTestResults, StrategyReport, Problem, Response } from '../../services/esipService';

// ===================================
// ESIP: 전략 리포트 화면
// ===================================

const { width } = Dimensions.get('window');

export default function ReportScreen() {
    const params = useLocalSearchParams<{
        sessionId: string;
        examType: string;
        responses: string;
        problems: string;
        studentName: string;
    }>();

    const [report, setReport] = useState<StrategyReport | null>(null);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        generateReport();
    }, []);

    const generateReport = async () => {
        try {
            const problems: Problem[] = JSON.parse(params.problems || '[]');
            const responses: Response[] = JSON.parse(params.responses || '[]');

            const result = await analyzeTestResults(
                problems,
                responses,
                params.studentName || 'Student'
            );

            setReport(result);
        } catch (error) {
            console.error('Report generation failed:', error);
        } finally {
            setIsLoading(false);
        }
    };

    const handleShare = async () => {
        if (!report) return;

        const message = `
📊 ESIP Strategy Report
Student: ${params.studentName}

📈 Score: ${report.rawScore}/${report.totalQuestions} (${report.accuracy}%)
⏱️ Time: ${Math.round(report.totalTimeSeconds / 60)} min

🎯 Potential Score: ${report.potentialScore}/${report.totalQuestions}

📝 Key Recommendations:
${report.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

Generated by ESIP - Exam Strategy Intelligent Profiler
        `.trim();

        await Share.share({ message });
    };

    if (isLoading) {
        return (
            <SafeAreaView style={styles.container}>
                <View style={styles.loadingContainer}>
                    <ActivityIndicator size="large" color={colors.accent.primary} />
                    <Text style={styles.loadingText}>Analyzing your performance...</Text>
                    <Text style={styles.loadingSubtext}>AI is identifying patterns and strategies</Text>
                </View>
            </SafeAreaView>
        );
    }

    if (!report) {
        return (
            <SafeAreaView style={styles.container}>
                <View style={styles.loadingContainer}>
                    <Ionicons name="alert-circle" size={48} color={colors.status.error} />
                    <Text style={styles.loadingText}>Analysis Failed</Text>
                    <TouchableOpacity style={styles.retryButton} onPress={() => router.back()}>
                        <Text style={styles.retryText}>Go Back</Text>
                    </TouchableOpacity>
                </View>
            </SafeAreaView>
        );
    }

    return (
        <SafeAreaView style={styles.container}>
            {/* 헤더 */}
            <View style={styles.header}>
                <TouchableOpacity onPress={() => router.replace('/')}>
                    <Ionicons name="close" size={24} color={colors.text.primary} />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Strategy Report</Text>
                <TouchableOpacity onPress={handleShare}>
                    <Ionicons name="share-outline" size={24} color={colors.text.primary} />
                </TouchableOpacity>
            </View>

            <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
                {/* 점수 서머리 */}
                <View style={styles.scoreCard}>
                    <View style={styles.scoreMain}>
                        <Text style={styles.scoreNumber}>{report.rawScore}</Text>
                        <Text style={styles.scoreTotal}>/{report.totalQuestions}</Text>
                    </View>
                    <Text style={styles.scorePercent}>{report.accuracy}%</Text>

                    <View style={styles.scoreMeta}>
                        <View style={styles.scoreMetaItem}>
                            <Ionicons name="time-outline" size={16} color={colors.text.muted} />
                            <Text style={styles.scoreMetaText}>
                                {Math.round(report.totalTimeSeconds / 60)} min
                            </Text>
                        </View>
                        <View style={styles.scoreMetaItem}>
                            <Ionicons name="speedometer-outline" size={16} color={colors.text.muted} />
                            <Text style={styles.scoreMetaText}>
                                {report.avgTimePerQuestion}s/q
                            </Text>
                        </View>
                    </View>
                </View>

                {/* 점수 예측 */}
                <View style={styles.predictionCard}>
                    <View style={styles.predictionHeader}>
                        <Ionicons name="trending-up" size={20} color={colors.status.success} />
                        <Text style={styles.predictionTitle}>Potential Score</Text>
                    </View>
                    <View style={styles.predictionContent}>
                        <View style={styles.predictionCurrent}>
                            <Text style={styles.predictionLabel}>Current</Text>
                            <Text style={styles.predictionValue}>{report.currentScore}</Text>
                        </View>
                        <Ionicons name="arrow-forward" size={24} color={colors.accent.primary} />
                        <View style={styles.predictionPotential}>
                            <Text style={styles.predictionLabel}>Potential</Text>
                            <Text style={[styles.predictionValue, styles.predictionValueHighlight]}>
                                {report.potentialScore}
                            </Text>
                        </View>
                    </View>
                    <Text style={styles.predictionNote}>
                        +{report.potentialScore - report.currentScore} points possible with strategy
                    </Text>
                </View>

                {/* 오류 패턴 */}
                <Text style={styles.sectionTitle}>Error Patterns Detected</Text>
                <View style={styles.errorPatternsContainer}>
                    {report.errorPatterns.length === 0 ? (
                        <View style={styles.noErrorsCard}>
                            <Ionicons name="checkmark-circle" size={32} color={colors.status.success} />
                            <Text style={styles.noErrorsText}>Great job! No major error patterns detected.</Text>
                        </View>
                    ) : (
                        report.errorPatterns.map((pattern, idx) => (
                            <View key={idx} style={styles.errorCard}>
                                <View style={styles.errorHeader}>
                                    <View style={[styles.errorIcon, getErrorStyle(pattern.type)]}>
                                        <Ionicons
                                            name={getErrorIcon(pattern.type)}
                                            size={16}
                                            color="#fff"
                                        />
                                    </View>
                                    <Text style={styles.errorType}>{formatErrorType(pattern.type)}</Text>
                                    <View style={styles.errorCount}>
                                        <Text style={styles.errorCountText}>{pattern.count}</Text>
                                    </View>
                                </View>
                                <Text style={styles.errorDescription}>{pattern.description}</Text>
                                <Text style={styles.errorExamples}>
                                    Questions: {pattern.examples.join(', ')}
                                </Text>
                            </View>
                        ))
                    )}
                </View>

                {/* 토픽 분석 */}
                <Text style={styles.sectionTitle}>Topic Performance</Text>
                <View style={styles.topicContainer}>
                    {report.topicAnalysis.map((topic, idx) => (
                        <View key={idx} style={styles.topicRow}>
                            <Text style={styles.topicName}>{topic.topic}</Text>
                            <View style={styles.topicBar}>
                                <View
                                    style={[
                                        styles.topicBarFill,
                                        { width: `${topic.accuracy}%` },
                                        getAccuracyColor(topic.accuracy),
                                    ]}
                                />
                            </View>
                            <Text style={styles.topicPercent}>{topic.accuracy}%</Text>
                        </View>
                    ))}
                </View>

                {/* Kill/Keep 리스트 */}
                <View style={styles.strategyRow}>
                    <View style={[styles.strategyCard, styles.killCard]}>
                        <View style={styles.strategyHeader}>
                            <Ionicons name="close-circle" size={20} color={colors.status.error} />
                            <Text style={styles.strategyTitle}>Kill List</Text>
                        </View>
                        <Text style={styles.strategySubtitle}>Skip these for now</Text>
                        {report.killList.length === 0 ? (
                            <Text style={styles.strategyItem}>None - keep practicing all!</Text>
                        ) : (
                            report.killList.map((item, idx) => (
                                <Text key={idx} style={styles.strategyItem}>• {item}</Text>
                            ))
                        )}
                    </View>

                    <View style={[styles.strategyCard, styles.keepCard]}>
                        <View style={styles.strategyHeader}>
                            <Ionicons name="checkmark-circle" size={20} color={colors.status.success} />
                            <Text style={styles.strategyTitle}>Keep List</Text>
                        </View>
                        <Text style={styles.strategySubtitle}>Must get right</Text>
                        {report.keepList.length === 0 ? (
                            <Text style={styles.strategyItem}>Build fundamentals first</Text>
                        ) : (
                            report.keepList.map((item, idx) => (
                                <Text key={idx} style={styles.strategyItem}>• {item}</Text>
                            ))
                        )}
                    </View>
                </View>

                {/* 시간 전략 */}
                <View style={styles.timeCard}>
                    <View style={styles.timeHeader}>
                        <Ionicons name="timer-outline" size={20} color={colors.accent.primary} />
                        <Text style={styles.timeTitle}>Time Strategy</Text>
                    </View>
                    <Text style={styles.timeText}>{report.timeStrategy}</Text>
                </View>

                {/* AI 추천 */}
                <Text style={styles.sectionTitle}>AI Recommendations</Text>
                <View style={styles.recommendationsCard}>
                    <Text style={styles.summaryText}>{report.summary}</Text>
                    <View style={styles.recommendationsList}>
                        {report.recommendations.map((rec, idx) => (
                            <View key={idx} style={styles.recommendationItem}>
                                <View style={styles.recommendationNumber}>
                                    <Text style={styles.recommendationNumberText}>{idx + 1}</Text>
                                </View>
                                <Text style={styles.recommendationText}>{rec}</Text>
                            </View>
                        ))}
                    </View>
                </View>

                {/* 하단 여백 */}
                <View style={{ height: 100 }} />
            </ScrollView>

            {/* 하단 버튼 */}
            <View style={styles.footer}>
                <TouchableOpacity
                    style={styles.footerButton}
                    onPress={() => router.replace('/test')}
                >
                    <Ionicons name="refresh" size={20} color={colors.text.primary} />
                    <Text style={styles.footerButtonText}>New Test</Text>
                </TouchableOpacity>
                <TouchableOpacity
                    style={[styles.footerButton, styles.footerButtonPrimary]}
                    onPress={() => router.replace('/')}
                >
                    <Ionicons name="home" size={20} color="#000" />
                    <Text style={styles.footerButtonTextPrimary}>Dashboard</Text>
                </TouchableOpacity>
            </View>
        </SafeAreaView>
    );
}

// Helper functions
const formatErrorType = (type: string) => {
    const labels: Record<string, string> = {
        careless: 'Careless Mistakes',
        conceptual_gap: 'Conceptual Gap',
        time_pressure: 'Time Pressure',
        guessed: 'Random Guessing',
        mental_fatigue: 'Mental Fatigue',
    };
    return labels[type] || type;
};

const getErrorIcon = (type: string): keyof typeof Ionicons.glyphMap => {
    const icons: Record<string, keyof typeof Ionicons.glyphMap> = {
        careless: 'alert-circle',
        conceptual_gap: 'help-circle',
        time_pressure: 'time',
        guessed: 'dice',
        mental_fatigue: 'battery-dead',
    };
    return icons[type] || 'alert';
};

const getErrorStyle = (type: string) => {
    const colors_map: Record<string, string> = {
        careless: '#F59E0B',
        conceptual_gap: '#EF4444',
        time_pressure: '#8B5CF6',
        guessed: '#6B7280',
        mental_fatigue: '#EC4899',
    };
    return { backgroundColor: colors_map[type] || '#6B7280' };
};

const getAccuracyColor = (accuracy: number) => {
    if (accuracy >= 80) return { backgroundColor: colors.status.success };
    if (accuracy >= 60) return { backgroundColor: '#EAB308' };
    if (accuracy >= 40) return { backgroundColor: '#F97316' };
    return { backgroundColor: colors.status.error };
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.bg.base,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: spacing.xl,
    },
    loadingText: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text.primary,
        marginTop: spacing.lg,
    },
    loadingSubtext: {
        fontSize: 14,
        color: colors.text.muted,
        marginTop: spacing.sm,
    },
    retryButton: {
        marginTop: spacing.xl,
        paddingHorizontal: spacing.xl,
        paddingVertical: spacing.md,
        backgroundColor: colors.accent.primary,
        borderRadius: radius.md,
    },
    retryText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#000',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.md,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.text.primary,
    },
    content: {
        flex: 1,
        paddingHorizontal: spacing.lg,
    },
    scoreCard: {
        backgroundColor: colors.accent.primary,
        padding: spacing.xl,
        borderRadius: radius.xl,
        alignItems: 'center',
        marginBottom: spacing.lg,
    },
    scoreMain: {
        flexDirection: 'row',
        alignItems: 'baseline',
    },
    scoreNumber: {
        fontSize: 64,
        fontWeight: '800',
        color: '#000',
    },
    scoreTotal: {
        fontSize: 24,
        fontWeight: '600',
        color: 'rgba(0,0,0,0.5)',
    },
    scorePercent: {
        fontSize: 20,
        fontWeight: '700',
        color: '#000',
        marginTop: spacing.xs,
    },
    scoreMeta: {
        flexDirection: 'row',
        gap: spacing.xl,
        marginTop: spacing.lg,
    },
    scoreMetaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.xs,
    },
    scoreMetaText: {
        fontSize: 14,
        color: 'rgba(0,0,0,0.6)',
    },
    predictionCard: {
        backgroundColor: colors.bg.card,
        padding: spacing.lg,
        borderRadius: radius.lg,
        borderWidth: 1,
        borderColor: colors.status.success,
        marginBottom: spacing.xl,
    },
    predictionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
        marginBottom: spacing.md,
    },
    predictionTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.status.success,
    },
    predictionContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing.xl,
    },
    predictionCurrent: {
        alignItems: 'center',
    },
    predictionPotential: {
        alignItems: 'center',
    },
    predictionLabel: {
        fontSize: 12,
        color: colors.text.muted,
        marginBottom: spacing.xs,
    },
    predictionValue: {
        fontSize: 32,
        fontWeight: '800',
        color: colors.text.primary,
    },
    predictionValueHighlight: {
        color: colors.status.success,
    },
    predictionNote: {
        fontSize: 12,
        color: colors.status.success,
        textAlign: 'center',
        marginTop: spacing.md,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.text.muted,
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: spacing.md,
        marginTop: spacing.lg,
    },
    errorPatternsContainer: {
        gap: spacing.md,
    },
    noErrorsCard: {
        backgroundColor: colors.bg.card,
        padding: spacing.xl,
        borderRadius: radius.lg,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.status.success,
    },
    noErrorsText: {
        fontSize: 14,
        color: colors.text.secondary,
        marginTop: spacing.md,
        textAlign: 'center',
    },
    errorCard: {
        backgroundColor: colors.bg.card,
        padding: spacing.lg,
        borderRadius: radius.lg,
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    errorHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.sm,
    },
    errorIcon: {
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: spacing.sm,
    },
    errorType: {
        flex: 1,
        fontSize: 16,
        fontWeight: '600',
        color: colors.text.primary,
    },
    errorCount: {
        backgroundColor: colors.bg.base,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.xs,
        borderRadius: radius.full,
    },
    errorCountText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.text.secondary,
    },
    errorDescription: {
        fontSize: 14,
        color: colors.text.secondary,
        lineHeight: 20,
        marginBottom: spacing.sm,
    },
    errorExamples: {
        fontSize: 12,
        color: colors.text.muted,
    },
    topicContainer: {
        backgroundColor: colors.bg.card,
        padding: spacing.lg,
        borderRadius: radius.lg,
        gap: spacing.md,
    },
    topicRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    topicName: {
        width: 80,
        fontSize: 13,
        color: colors.text.secondary,
    },
    topicBar: {
        flex: 1,
        height: 8,
        backgroundColor: colors.bg.base,
        borderRadius: 4,
        marginHorizontal: spacing.sm,
        overflow: 'hidden',
    },
    topicBarFill: {
        height: '100%',
        borderRadius: 4,
    },
    topicPercent: {
        width: 40,
        fontSize: 13,
        fontWeight: '600',
        color: colors.text.primary,
        textAlign: 'right',
    },
    strategyRow: {
        flexDirection: 'row',
        gap: spacing.md,
        marginTop: spacing.lg,
    },
    strategyCard: {
        flex: 1,
        padding: spacing.lg,
        borderRadius: radius.lg,
        borderWidth: 1,
    },
    killCard: {
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        borderColor: colors.status.error,
    },
    keepCard: {
        backgroundColor: 'rgba(34, 197, 94, 0.1)',
        borderColor: colors.status.success,
    },
    strategyHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.xs,
        marginBottom: spacing.xs,
    },
    strategyTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.text.primary,
    },
    strategySubtitle: {
        fontSize: 11,
        color: colors.text.muted,
        marginBottom: spacing.md,
    },
    strategyItem: {
        fontSize: 12,
        color: colors.text.secondary,
        marginTop: spacing.xs,
    },
    timeCard: {
        backgroundColor: colors.bg.card,
        padding: spacing.lg,
        borderRadius: radius.lg,
        marginTop: spacing.lg,
        borderWidth: 1,
        borderColor: colors.accent.primary,
    },
    timeHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
        marginBottom: spacing.md,
    },
    timeTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.accent.primary,
    },
    timeText: {
        fontSize: 14,
        color: colors.text.secondary,
        lineHeight: 22,
    },
    recommendationsCard: {
        backgroundColor: colors.bg.card,
        padding: spacing.lg,
        borderRadius: radius.lg,
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    summaryText: {
        fontSize: 14,
        color: colors.text.secondary,
        lineHeight: 22,
        marginBottom: spacing.lg,
        fontStyle: 'italic',
    },
    recommendationsList: {
        gap: spacing.md,
    },
    recommendationItem: {
        flexDirection: 'row',
        gap: spacing.md,
    },
    recommendationNumber: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: colors.accent.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    recommendationNumberText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#000',
    },
    recommendationText: {
        flex: 1,
        fontSize: 14,
        color: colors.text.primary,
        lineHeight: 22,
    },
    footer: {
        flexDirection: 'row',
        gap: spacing.md,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.lg,
        borderTopWidth: 1,
        borderTopColor: colors.border.default,
    },
    footerButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing.sm,
        paddingVertical: spacing.lg,
        borderRadius: radius.lg,
        backgroundColor: colors.bg.card,
        borderWidth: 1,
        borderColor: colors.border.default,
    },
    footerButtonPrimary: {
        backgroundColor: colors.accent.primary,
        borderColor: colors.accent.primary,
    },
    footerButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text.primary,
    },
    footerButtonTextPrimary: {
        fontSize: 14,
        fontWeight: '700',
        color: '#000',
    },
});
